---
- hosts: web_nodes
  become: yes
  vars:
  public1: 
  private1: 
  private2:
  roles:
  - ngnix
  
  tasks:
   - include_tasks: task/os-dependencies.yml
   
- hosts stats_nodes
  become: yes
  vars:
   metrics_db_name: "name"
   metrics_db_pas: "password"
   metrics_db_user: "user"
   datasource_name: "my-influx"
   grafana_http_port: 3000
   telegraf_configuration: "telegraf_default.conf"
  roles:
   - grafana 
   - telegraf 
   - influxdb
  tasks:
   - include_tasks: tasks/configure-grafana.yml
 
- hosts: app_nodes
  become: yes
  vars:
    jar_location: carrental/car_rental.jar
    app_location: /opt/carrental/car_rental.jar
    app_user: carrental
  roles:
     - application
     - telegraf


   
