---
- name: Install Epel
    yum:
      name: "{{epel_link}}"
      state: present
  - name: Install Nginx
    yum:
      name: nginx
      state: latest
  - template:
      src: templates/nginx.conf
      dest: /etc/nginx/conf.d/nginx.conf
  - name: Restart Nginx
    service:
      name: nginx
      state: restarted
#setup_proxy